# Python parada Análise de dados - Pandas

Será utilizada a Base de imóveis obtidas no Kaggle.

O download da base pode ser feito atravéz do [link](https://github.com/minerandodados/mdrepo/blob/master/kc_house_data.csv)

In [2]:
# Importando o Pandas
import pandas as pd

In [3]:
# Lendo uma base de dados no formato .csv.
# O parâmetro sep é usado para definir qual o separador entre os dados 
# O parametro header informa qual linha está as colunas ou se elas não existe
# Se não existe colunas (header=None) o pandas dará um número para cada atributo da base.
arquivo = 'kc_house_data.csv'
dataset = pd.read_csv(arquivo,sep=',',header=0)

In [4]:
# Imprime o tipo da ariável datase
# Dataframe é uma estrutura de dados onde linhas podem ter colunas de diferentes tipos.
type(dataset)

pandas.core.frame.DataFrame

In [5]:
# Método head() imprime as 5 linhas iniciais do dataframe.
dataset.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3.0,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3.0,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2.0,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4.0,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3.0,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [6]:
# parâmetro index_col informa a coluna na qual o datafram será indexado
dataset = pd.read_csv(arquivo,sep=',',index_col='date')
dataset.head()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
date,,,,,,,,,,,,,,,,,,,,
20141013T000000,7129300520,221900.0,3.0,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
20141209T000000,6414100192,538000.0,3.0,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
20150225T000000,5631500400,180000.0,2.0,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
20141209T000000,2487200875,604000.0,4.0,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
20150218T000000,1954400510,510000.0,3.0,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [7]:
# O parâmetro usecols especifica as colunas que deve ser lidas pelo pandas, ignorando todas as outras do arquivo lido
dataset = pd.read_csv(arquivo,sep=',',usecols=['id','date','price','bedrooms'])
dataset.head()

           id             date     price  bedrooms
0  7129300520  20141013T000000  221900.0       3.0
1  6414100192  20141209T000000  538000.0       3.0
2  5631500400  20150225T000000  180000.0       2.0
3  2487200875  20141209T000000  604000.0       4.0
4  1954400510  20150218T000000  510000.0       3.0

In [8]:
dataset = pd.read_csv(arquivo,sep=',',header=0)
# Imprime alem das 5 linhas
dataset.head(100)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3.0,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3.0,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2.0,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4.0,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3.0,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000.0,4.0,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,1321400060,20140627T000000,257500.0,3.0,2.25,1715,6819,2.0,0,0,...,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,2008000270,20150115T000000,291850.0,3.0,1.50,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
8,2414600126,20150415T000000,229500.0,3.0,1.00,1780,7470,1.0,0,0,...,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
9,3793500160,20150312T000000,323000.0,3.0,2.50,1890,6560,2.0,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570
10,1736800520,20150403T000000,662500.0,3.0,2.50,3560,9796,1.0,0,0,...,8,1860,1700,1965,0,98007,47.6007,-122.145,2210,8925
11,9212900260,20140527T000000,468000.0,2.0,1.00,1160,6000,NaN,0,0,...,7,860,300,1942,0,98115,47.6900,-122.292,1330,6000
12,114101516,20140528T000000,310000.0,3.0,1.00,1430,19901,1.5,0,0,...,7,1430,0,1927,0,98028,47.7558,-122.229,1780,12697
13,6054650070,20141007T000000,400000.0,3.0,1.75,1370,9680,1.0,0,0,...,7,1370,0,1977,0,98074,47.6127,-122.045,1370,10208
14,1175000570,20150312T000000,530000.0,5.0,2.00,1810,4850,1.5,0,0,...,7,1810,0,1900,0,98107,47.6700,-122.394,1360,4850
15,9297300055,20150124T000000,650000.0,4.0,3.00,2950,5000,2.0,0,3,...,9,1980,970,1979,0,98126,47.5714,-122.375,2140,4000
16,1875500060,20140731T000000,395000.0,3.0,2.00,1890,14040,2.0,0,0,...,7,1890,0,1994,0,98019,47.7277,-121.962,1890,14018
17,6865200140,20140529T000000,485000.0,4.0,1.00,1600,4300,1.5,0,0,...,7,1600,0,1916,0,98103,47.6648,-122.343,1610,4300
18,16000397,20141205T000000,189000.0,2.0,1.00,1200,9850,1.0,0,0,...,7,1200,0,1921,0,98002,47.3089,-122.210,1060,5095
19,7983200060,20150424T000000,230000.0,3.0,1.00,1250,9774,1.0,0,0,...,7,1250,0,1969,0,98003,47.3343,-122.306,1280,8850
20,6300500875,20140514T000000,385000.0,4.0,1.75,1620,4980,1.0,0,0,...,7,860,760,1947,0,98133,47.7025,-122.341,1400,4980
21,2524049179,20140826T000000,2000000.0,3.0,2.75,3050,44867,1.0,0,4,...,9,2330,720,1968,0,98040,47.5316,-122.233,4110,20336
22,7137970340,20140703T000000,285000.0,5.0,2.50,2270,6300,2.0,0,0,...,8,2270,0,1995,0,98092,47.3266,-122.169,2240,7005
23,8091400200,20140516T000000,252700.0,2.0,1.50,1070,9643,1.0,0,0,...,7,1070,0,1985,0,98030,47.3533,-122.166,1220,8386
24,3814700200,20141120T000000,329000.0,3.0,2.25,2450,6500,2.0,0,0,...,8,2450,0,1985,0,98030,47.3739,-122.172,2200,6865
25,1202000200,20141103T000000,233000.0,3.0,2.00,1710,4697,1.5,0,0,...,6,1710,0,1941,0,98002,47.3048,-122.218,1030,4705
26,1794500383,20140626T000000,937000.0,3.0,1.75,2450,2691,2.0,0,0,...,8,1750,700,1915,0,98119,47.6386,-122.360,1760,3573
27,3303700376,20141201T000000,667000.0,3.0,1.00,1400,1581,1.5,0,0,...,8,1400,0,1909,0,98112,47.6221,-122.314,1860,3861
28,5101402488,20140624T000000,438000.0,3.0,1.75,1520,6380,1.0,0,0,...,7,790,730,1948,0,98115,47.6950,-122.304,1520,6235
29,1873100390,20150302T000000,719000.0,4.0,2.50,2570,7173,2.0,0,0,...,8,2570,0,2005,0,98052,47.7073,-122.110,2630,6026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,1525059190,20140912T000000,1040000.0,5.0,3.25,4770,50094,1.0,0,0,...,11,3070,1700,1973,0,98005,47.6525,-122.160,3530,38917
71,1049000060,20150105T000000,325000.0,3.0,2.00,1260,5612,1.0,0,0,...,7,1260,0,1972,0,98034,47.7362,-122.179,1640,4745
72,8820901275,20140610T000000,571000.0,4.0,2.00,2750,7807,1.5,0,0,...,7,2250,500,1916,0,98125,47.7168,-122.287,1510,7807
73,5416510140,20140710T000000,360000.0,4.0,2.50,2380,5000,2.0,0,0,...,8,2380,0,2005,0,98038,47.3608,-122.036,2420,5000
74,3444100400,20150316T000000,349000.0,3.0,1.75,1790,50529,1.0,0,0,...,7,1090,700,1965,0,98042,47.3511,-122.073,1940,50529
75,3276920270,20141105T000000,832500.0,4.0,4.00,3430,35102,2.0,0,0,...,10,2390,1040,1986,0,98075,47.5822,-121.987,3240,35020
76,4036801170,20141013T000000,380000.0,4.0,1.75,1760,7300,1.0,0,0,...,7,880,880,1956,0,98008,47.6034,-122.125,1680,7500
77,2391600320,20150420T000000,480000.0,3.0,1.00,1040,5060,1.0,0,0,...,7,1040,0,1941,0,98116,47.5636,-122.394,890,5060
78,6300000287,20140609T000000,410000.0,3.0,1.00,1410,5060,1.0,0,0,...,7,910,500,1956,0,98133,47.7073,-122.340,1130,5693
79,1531000030,20150323T000000,720000.0,4.0,2.50,3450,39683,2.0,0,0,...,10,3450,0,2002,0,98010,47.3420,-122.025,3350,39750
80,5104520400,20141202T000000,390000.0,3.0,2.50,2350,5100,2.0,0,0,...,8,2350,0,2003,0,98038,47.3512,-122.008,2350,5363
81,7437100340,20141222T000000,360000.0,4.0,2.50,1900,5889,2.0,0,0,...,7,1900,0,1992,0,98038,47.3490,-122.031,1870,6405
82,9418400240,20141028T000000,355000.0,2.0,1.00,2020,6720,1.0,0,0,...,7,1010,1010,1948,0,98118,47.5474,-122.291,1720,6720
83,1523059105,20150128T000000,356000.0,3.0,1.50,1680,8712,1.0,0,0,...,8,1680,0,1964,0,98059,47.4811,-122.149,1850,8797
84,1133000671,20140602T000000,315000.0,3.0,1.00,960,6634,1.0,0,0,...,6,960,0,1952,0,98125,47.7264,-122.310,1570,7203
85,4232902595,20141114T000000,940000.0,3.0,1.50,2140,3600,2.0,0,0,...,9,1900,240,1925,0,98119,47.6337,-122.365,2020,4800
86,2599001200,20141103T000000,305000.0,5.0,2.25,2660,8400,1.5,0,0,...,7,2660,0,1961,0,98092,47.2909,-122.189,1590,8165
87,3342103156,20140618T000000,461000.0,3.0,3.25,2770,6278,2.0,0,0,...,9,1980,790,2006,0,98056,47.5228,-122.199,1900,7349
88,1332700270,20140519T000000,215000.0,NaN,2.25,1610,2040,2.0,0,0,...,7,1610,0,1979,0,98056,47.5180,-122.194,1950,2025
89,3869900162,20140904T000000,335000.0,2.0,1.75,1030,1066,2.0,0,0,...,7,765,265,2006,0,98136,47.5394,-122.387,1030,1106
90,2791500270,20140522T000000,243500.0,4.0,2.50,1980,7403,2.0,0,0,...,7,1980,0,1988,0,98023,47.2897,-122.372,1980,7510
91,5036300431,20150311T000000,1099880.0,5.0,2.75,3520,6353,2.0,0,0,...,10,3520,0,2001,0,98199,47.6506,-122.391,2520,6250
92,4168000060,20150226T000000,153000.0,3.0,1.00,1200,10500,1.0,0,0,...,7,1200,0,1962,0,98023,47.3220,-122.351,1350,10500
93,6021501535,20140725T000000,430000.0,3.0,1.50,1580,5000,1.0,0,0,...,8,1290,290,1939,0,98117,47.6870,-122.386,1570,4500
94,6021501535,20141223T000000,700000.0,3.0,1.50,1580,5000,1.0,0,0,...,8,1290,290,1939,0,98117,47.6870,-122.386,1570,4500
95,1483300570,20140908T000000,905000.0,4.0,2.50,3300,10250,1.0,0,0,...,7,2390,910,1946,1991,98040,47.5873,-122.249,1950,6045
96,3422049190,20150330T000000,247500.0,3.0,1.75,1960,15681,1.0,0,0,...,7,1960,0,1967,0,98032,47.3576,-122.277,1750,15616
97,1099611230,20140912T000000,199000.0,4.0,1.50,1160,6400,1.0,0,0,...,7,1160,0,1975,0,98023,47.3036,-122.378,1160,6400
98,722079104,20140711T000000,314000.0,3.0,1.75,1810,41800,1.0,0,0,...,7,1210,600,1980,0,98038,47.4109,-121.958,1650,135036
99,7338200240,20140516T000000,437500.0,3.0,2.50,2320,36847,2.0,0,2,...,9,2320,0,1992,0,98045,47.4838,-121.714,2550,35065

In [9]:
# O atributo columns retorna o nome das counas do dataframe
dataset.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [10]:
# Método count() retorna a quantidade de linhas de todas as colunas.
dataset.count()

id               21613
date             21613
price            21613
bedrooms         21609
bathrooms        21613
sqft_living      21613
sqft_lot         21613
floors           21612
waterfront       21613
view             21613
condition        21613
grade            21613
sqft_above       21613
sqft_basement    21613
yr_built         21613
yr_renovated     21613
zipcode          21613
lat              21613
long             21613
sqft_living15    21613
sqft_lot15       21613
dtype: int64

In [12]:
# Método describe() exibe informaçoes estatísticas da base de dados.
# Várias informações como desvio padrão, média valor mínimo e valor máximo de colunas
dataset.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21609.000000,21613.000000,21613.000000,2.161300e+04,21612.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370910,2.114757,2079.899736,1.510697e+04,1.494332,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930084,0.770163,918.440897,4.142051e+04,0.539991,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [18]:
# Imprime as ultimas 5 linhas.
dataset.tail()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,263000018,20140521T000000,360000.0,3.0,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4.0,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2.0,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3.0,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2.0,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [19]:
# Imprime as ultimas 100 linhas.
dataset.tail(100)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21513,1023059465,20140513T000000,505000.0,4.0,2.50,2790,5602,2.0,0,0,...,8,2790,0,2009,0,98059,47.4959,-122.150,2790,5309
21514,3262300818,20150227T000000,1865000.0,4.0,3.75,3790,8797,2.0,0,0,...,11,3290,500,2006,0,98039,47.6351,-122.236,2660,12150
21515,2937300040,20141215T000000,942990.0,4.0,2.50,3570,6218,2.0,0,0,...,9,3570,0,2014,0,98052,47.7046,-122.123,3230,5972
21516,2768100206,20141001T000000,440000.0,3.0,2.25,1230,1097,3.0,0,0,...,8,1230,0,2009,0,98107,47.6697,-122.372,1420,1437
21517,7904700134,20140626T000000,390000.0,3.0,3.25,1370,913,2.0,0,0,...,8,1100,270,2006,0,98116,47.5636,-122.388,1370,915
21518,9521100867,20140711T000000,475000.0,3.0,3.25,1380,1121,3.0,0,0,...,8,1380,0,2008,0,98103,47.6617,-122.349,1310,1405
21519,1702901618,20150407T000000,420000.0,1.0,2.00,1070,675,2.0,0,0,...,8,880,190,2007,0,98118,47.5574,-122.284,1220,788
21520,7237550100,20140825T000000,1408760.0,4.0,4.00,4920,50621,2.0,0,0,...,10,4280,640,2012,0,98053,47.6575,-122.006,4920,74052
21521,7430500110,20141209T000000,1378000.0,5.0,3.50,5150,12230,2.0,0,2,...,10,3700,1450,2007,0,98008,47.6249,-122.090,2940,13462
21522,603000555,20150302T000000,462500.0,6.0,3.00,2390,4000,2.0,0,0,...,7,2390,0,2014,0,98118,47.5173,-122.286,1680,5000
21523,3304300300,20150507T000000,579950.0,4.0,2.75,2460,8643,2.0,0,0,...,9,2460,0,2011,0,98059,47.4828,-122.133,3110,8626
21524,6453550090,20150505T000000,861111.0,4.0,2.50,3650,7090,2.0,0,0,...,10,3650,0,2008,0,98074,47.6060,-122.052,3860,7272
21525,2625069038,20141124T000000,1450000.0,4.0,3.50,4300,108865,2.0,0,0,...,11,4300,0,2014,0,98074,47.6258,-122.005,4650,107498
21526,1760650820,20150428T000000,290000.0,3.0,2.25,1610,3764,2.0,0,0,...,7,1610,0,2012,0,98042,47.3589,-122.083,1610,3825
21527,9578060230,20140618T000000,535000.0,4.0,2.50,2610,4595,2.0,0,0,...,8,2610,0,2008,0,98028,47.7728,-122.235,2440,4588
21528,3416600750,20150217T000000,585000.0,3.0,2.50,1750,1381,3.0,0,0,...,8,1750,0,2008,0,98122,47.6021,-122.294,1940,4800
21529,2487200490,20140623T000000,670000.0,3.0,2.50,3310,5300,2.0,0,2,...,8,2440,870,2008,0,98136,47.5178,-122.389,2140,7500
21530,8964800330,20150407T000000,3000000.0,4.0,3.75,5090,14823,1.0,0,0,...,11,4180,910,2013,0,98004,47.6200,-122.207,3030,12752
21531,5637500082,20141203T000000,346000.0,3.0,2.00,1060,1184,2.0,0,0,...,7,730,330,2006,0,98136,47.5443,-122.385,1270,1601
21532,324069112,20140617T000000,1325000.0,4.0,4.00,4420,16526,2.0,0,0,...,11,4420,0,2013,0,98075,47.5914,-122.027,3510,50447
21533,524059322,20150226T000000,999999.0,3.0,2.50,2100,4097,2.0,0,0,...,9,2100,0,2008,0,98004,47.5983,-122.200,1780,4764
21534,889000025,20140811T000000,599000.0,3.0,1.75,1650,1180,3.0,0,0,...,8,1650,0,2014,0,98105,47.6636,-122.319,1720,1960
21535,2909310100,20141015T000000,332000.0,4.0,2.50,2380,5737,2.0,0,0,...,7,2380,0,2010,0,98023,47.2815,-122.356,2380,5396
21536,8562780180,20140612T000000,336750.0,2.0,2.25,1170,1011,2.0,0,0,...,7,1170,0,2009,0,98027,47.5321,-122.073,1240,750
21537,1043000100,20141211T000000,370000.0,4.0,2.50,2531,6843,2.0,0,0,...,8,2531,0,2013,0,98030,47.3850,-122.189,2604,6238
21538,1865400076,20140509T000000,324000.0,3.0,2.25,998,904,2.0,0,0,...,7,798,200,2007,0,98117,47.6983,-122.367,998,1110
21539,8902000201,20150219T000000,338500.0,3.0,2.25,1333,1470,3.0,0,3,...,7,1333,0,2009,0,98125,47.7058,-122.302,1360,1680
21540,715010530,20150113T000000,1881580.0,5.0,3.50,4410,13000,2.0,0,3,...,10,2920,1490,2014,0,98006,47.5382,-122.111,5790,12969
21541,4253400100,20150410T000000,402723.0,3.0,2.75,1160,1073,2.0,0,0,...,7,880,280,2007,0,98144,47.5788,-122.315,1250,5400
21542,3874900085,20150227T000000,715000.0,4.0,3.25,2630,7770,2.0,0,0,...,9,2630,0,2014,0,98126,47.5459,-122.377,1370,7770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21583,2025049203,20140610T000000,399950.0,2.0,1.00,710,1157,2.0,0,0,...,7,710,0,1943,0,98102,47.6413,-122.329,1370,1173
21584,952006823,20141202T000000,380000.0,3.0,2.50,1260,900,2.0,0,0,...,7,940,320,2007,0,98116,47.5621,-122.384,1310,1415
21585,3832050760,20140828T000000,270000.0,3.0,2.50,1870,5000,2.0,0,0,...,7,1870,0,2009,0,98042,47.3339,-122.055,2170,5399
21586,2767604724,20141015T000000,505000.0,2.0,2.50,1430,1201,3.0,0,0,...,8,1430,0,2009,0,98107,47.6707,-122.381,1430,1249
21587,6632300207,20150305T000000,385000.0,3.0,2.50,1520,1488,3.0,0,0,...,8,1520,0,2006,0,98125,47.7337,-122.309,1520,1497
21588,2767600688,20141113T000000,414500.0,2.0,1.50,1210,1278,2.0,0,0,...,8,1020,190,2007,0,98117,47.6756,-122.375,1210,1118
21589,7570050450,20140910T000000,347500.0,3.0,2.50,2540,4760,2.0,0,0,...,8,2540,0,2010,0,98038,47.3452,-122.022,2540,4571
21590,7430200100,20140514T000000,1222500.0,4.0,3.50,4910,9444,1.5,0,0,...,11,3110,1800,2007,0,98074,47.6502,-122.066,4560,11063
21591,4140940150,20141002T000000,572000.0,4.0,2.75,2770,3852,2.0,0,0,...,8,2770,0,2014,0,98178,47.5001,-122.232,1810,5641
21592,1931300412,20150416T000000,475000.0,3.0,2.25,1190,1200,3.0,0,0,...,8,1190,0,2008,0,98103,47.6542,-122.346,1180,1224
21593,8672200110,20150317T000000,1088000.0,5.0,3.75,4170,8142,2.0,0,2,...,10,4170,0,2006,0,98056,47.5354,-122.181,3030,7980
21594,5087900040,20141017T000000,350000.0,4.0,2.75,2500,5995,2.0,0,0,...,8,2500,0,2008,0,98042,47.3749,-122.107,2530,5988
21595,1972201967,20141031T000000,520000.0,2.0,2.25,1530,981,3.0,0,0,...,8,1480,50,2006,0,98103,47.6533,-122.346,1530,1282
21596,7502800100,20140813T000000,679950.0,5.0,2.75,3600,9437,2.0,0,0,...,9,3600,0,2014,0,98059,47.4822,-122.131,3550,9421
21597,191100405,20150421T000000,1575000.0,4.0,3.25,3410,10125,2.0,0,0,...,10,3410,0,2007,0,98040,47.5653,-122.223,2290,10125
21598,8956200760,20141013T000000,541800.0,4.0,2.50,3118,7866,2.0,0,2,...,9,3118,0,2014,0,98001,47.2931,-122.264,2673,6500
21599,7202300110,20140915T000000,810000.0,4.0,3.00,3990,7838,2.0,0,0,...,9,3990,0,2003,0,98053,47.6857,-122.046,3370,6814
21600,249000205,20141015T000000,1537000.0,5.0,3.75,4470,8088,2.0,0,0,...,11,4470,0,2008,0,98004,47.6321,-122.200,2780,8964
21601,5100403806,20150407T000000,467000.0,3.0,2.50,1425,1179,3.0,0,0,...,8,1425,0,2008,0,98125,47.6963,-122.318,1285,1253
21602,844000965,20140626T000000,224000.0,3.0,1.75,1500,11968,1.0,0,0,...,6,1500,0,2014,0,98010,47.3095,-122.002,1320,11303
21603,7852140040,20140825T000000,507250.0,3.0,2.50,2270,5536,2.0,0,0,...,8,2270,0,2003,0,98065,47.5389,-121.881,2270,5731
21604,9834201367,20150126T000000,429000.0,3.0,2.00,1490,1126,3.0,0,0,...,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
21605,3448900210,20141014T000000,610685.0,4.0,2.50,2520,6023,2.0,0,0,...,9,2520,0,2014,0,98056,47.5137,-122.167,2520,6023
21606,7936000429,20150326T000000,1007500.0,4.0,3.50,3510,7200,2.0,0,0,...,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200
21607,2997800021,20150219T000000,475000.0,3.0,2.50,1310,1294,2.0,0,0,...,8,1180,130,2008,0,98116,47.5773,-122.409,1330,1265
21608,263000018,20140521T000000,360000.0,3.0,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4.0,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2.0,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3.0,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2.0,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [16]:
# Imprime uma amostra aleatória do dataset
dataset.sample(5)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
4325,3876300600,20141212T000000,371000.0,4.0,1.75,1610,11305,1.0,0,0,...,7,1610,0,1968,0,98034,47.7270,-122.176,1870,11850
14243,2397100155,20150224T000000,589000.0,3.0,1.75,920,3600,1.0,0,0,...,6,820,100,1904,0,98119,47.6386,-122.365,1620,3600
1038,5104511040,20150220T000000,380000.0,4.0,2.50,2000,6921,2.0,0,0,...,8,2000,0,2003,0,98038,47.3559,-122.014,2430,6339
5662,686900010,20140528T000000,898000.0,5.0,1.50,2680,28014,1.0,0,0,...,8,1450,1230,1963,0,98004,47.6348,-122.196,2900,22180
7433,9362000080,20150316T000000,1600000.0,5.0,3.50,4050,20925,2.0,0,3,...,10,3020,1030,1973,2005,98040,47.5348,-122.241,3880,18321

In [22]:
# Retorna em formato de tupla a quatidade de linhas e colunas do dataset => (linhas,colunas)
dataset.shape

(21613, 21)

In [24]:
# Imprime informações sobre colunas e uso de memória.
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
id               21613 non-null int64
date             21613 non-null object
price            21613 non-null float64
bedrooms         21609 non-null float64
bathrooms        21613 non-null float64
sqft_living      21613 non-null int64
sqft_lot         21613 non-null int64
floors           21612 non-null float64
waterfront       21613 non-null int64
view             21613 non-null int64
condition        21613 non-null int64
grade            21613 non-null int64
sqft_above       21613 non-null int64
sqft_basement    21613 non-null int64
yr_built         21613 non-null int64
yr_renovated     21613 non-null int64
zipcode          21613 non-null int64
lat              21613 non-null float64
long             21613 non-null float64
sqft_living15    21613 non-null int64
sqft_lot15       21613 non-null int64
dtypes: float64(6), int64(14), object(1)
memory usage: 3.5+ MB